---
name: MooseX-ClassAttribute
version: 0.02
author:
  - 'Dave Rolsky, C<< <autarch@urth.org> >>'
abstract: Declare class attributes Moose-style
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  B: 0
  Exporter: 0
  Moose: 0.26
  Sub::Name: 0
build_requires:
  Scalar::Util: 0
  Test::More: 0
provides:
  MooseX::ClassAttribute:
    file: lib/MooseX/ClassAttribute.pm
    version: 0.02
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
