---
abstract: 'Declare class attributes Moose-style'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  Test::Fatal: 0
  Test::More: 0.88
  Test::Requires: 0.05
  vars: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300031, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-ClassAttribute
requires:
  List::MoreUtils: 0
  Moose: 2.00
  Moose::Exporter: 0
  Moose::Meta::Role::Attribute: 0
  Moose::Role: 0
  Moose::Util: 0
  Moose::Util::MetaRole: 0
  Scalar::Util: 0
  namespace::autoclean: 0.11
  namespace::clean: 0.20
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=MooseX-ClassAttribute
  repository: git://git.moose.perl.org/MooseX-ClassAttribute.git
version: 0.27
